### ISSUE TITLE
Migrating from ant to gradle

### ISSUE THREAD

**Issue by rosedawson75** [nagaseshadri/oracle-commerce-gradle#3]
Hi Nagaseshadri,

I am trying to convert my ant build script to gradle.

I am getting "There is no installed ATG platform or application package containing an AppModule ....." error. I am able to run the ant build successfully. All the environment variables are set.

Am using Exec to run runAssembler.bat and passing arguments to it. 

should I need to explicitly pass environment variables to Exec as arguments ?

**Comment by nagaseshadri** [comment]
Looks like your ATG module is not inside DYNAMO_ROOT - for Example...

if you have your code workspace in /workspace/MyModule.....you need to make
sure you try and create a symbolic link or copy the module folder inside
your ATG installation folder , say /opt/ATG/ATG11.2 - so you have a folder
like ﻿﻿/opt/ATG/ATG11.2/MyModule  - assuming MyModule is the name of your
module that you are specifying in your runAssembler -m

Are you trying to use the oracle-commerce-gradle plugin or just converting
your ant -> gradle ????

-Naga

**Comment by rosedawson75** [comment]
My OS is windows. My modules is inside DYNAMO_ROOT only "C:\BCI\ATG\ATG11.2\BCI".

I tried to install atg pugin but am getting an error. PFA for reference.
![gradleatg](https://cloud.githubusercontent.com/assets/8309327/16892811/01b165ee-4b3e-11e6-8fc5-b24d0358773c.PNG)

I am just trying to run runAssembler command directly now just to see whether it works or not for now. Below is the task i created for this.

task hello(type:Exec)  {
     commandLine 'runAssembler.bat', '-overwrite' , 'C:/BCI/ATG/ATG11.2/BCI/build/${env.DEPLOY_PATH}/BCI-Store.ear', '-m', 'BCI.BCIREST DafEar.Admin ContentMgmt DCS.PublishingAgent' 
}

**Comment by nagaseshadri** [comment]
hey you dont need the oracle-commerce-gradle project cloned in your
local..unless you are planning to extend the plugin itself...

Refere this test-atg-module GitHub project's build.gradle file to know how
to use the oracle-commerce-gradle plugin for your project...remember its
developed and tested on Oracle Linux...

https://github.com/nagaseshadri/test-atg-module/blob/master/build.gradle

-Naga
